/**
 * The anthology. Four historical tests + a custom sandbox.
 * World frame: ground zero at the origin, +X = east, −Z = north, +Y = up. 1 unit = 1 m.
 */

export const ENVIRONMENTS = {
  desert: {
    id: 'desert',
    name: 'Jornada del Muerto, New Mexico',
    terrain: 'desert',
    water: false,
    groundType: 'soil',
    hdri: 'qwantani_dawn_puresky',
    envIntensity: 0.55,
    bgIntensity: 0.6,
    exposure: 0.9,
    fog: [0.62, 0.64, 0.7],
    fogDensity: 1.0 / 60000,
    visibility: 40000,
    humidity: 0.35,
    textures: { base: 'gravelly_sand', detail: 'dry_ground_rocks', rock: 'rock_face', special: 'mud_cracked_dry_03' },
    dustColor: [0.62, 0.52, 0.4],
    wind: { dir: 200, speed: 6 },
  },
  lagoon: {
    id: 'lagoon',
    name: 'Bikini Lagoon, Marshall Islands',
    terrain: 'atoll',
    water: true,
    groundType: 'coral',
    hdri: 'kloofendal_48d_partly_cloudy_puresky',
    envIntensity: 1.0,
    bgIntensity: 1.0,
    exposure: 0.8,
    fog: [0.7, 0.78, 0.88],
    fogDensity: 1.0 / 90000,
    visibility: 50000,
    humidity: 0.95,
    textures: { base: 'coast_sand_01', detail: 'coral_ground_02', rock: 'coral_gravel', special: 'coast_sand_01' },
    dustColor: [0.86, 0.84, 0.8],
    wind: { dir: 70, speed: 7 },
  },
  atoll: {
    id: 'atoll',
    name: 'Namu Reef, Bikini Atoll',
    terrain: 'atoll',
    water: true,
    groundType: 'coral',
    hdri: 'qwantani_sunrise_puresky',
    envIntensity: 0.8,
    bgIntensity: 0.85,
    exposure: 0.85,
    fog: [0.78, 0.7, 0.66],
    fogDensity: 1.0 / 120000,
    visibility: 60000,
    humidity: 0.85,
    textures: { base: 'coast_sand_01', detail: 'coral_ground_02', rock: 'coral_gravel', special: 'coast_sand_01' },
    dustColor: [0.9, 0.88, 0.84],
    wind: { dir: 260, speed: 12 }, // upper winds carried Bravo's fallout east
  },
  arctic: {
    id: 'arctic',
    name: 'Sukhoy Nos, Novaya Zemlya',
    terrain: 'arctic',
    water: true,
    groundType: 'snow',
    hdri: 'syferfontein_1d_clear_puresky',
    envIntensity: 0.7,
    bgIntensity: 0.75,
    exposure: 0.85,
    fog: [0.72, 0.76, 0.84],
    fogDensity: 1.0 / 140000,
    visibility: 90000,
    humidity: 0.6,
    textures: { base: 'snow_02', detail: 'snow_field_aerial', rock: 'rock_face', special: 'snow_02' },
    dustColor: [0.9, 0.92, 0.95],
    wind: { dir: 290, speed: 10 },
  },
};

export const SKY_PRESETS = [
  { id: 'scenario', name: 'Historical sky' },
  { id: 'qwantani_night_puresky', name: 'Night' },
  { id: 'qwantani_dawn_puresky', name: 'Blue hour' },
  { id: 'qwantani_sunrise_puresky', name: 'Sunrise' },
  { id: 'kloofendal_43d_clear_puresky', name: 'Clear noon' },
  { id: 'kloofendal_48d_partly_cloudy_puresky', name: 'Cumulus' },
  { id: 'kloofendal_overcast_puresky', name: 'Overcast' },
  { id: 'qwantani_dusk_2_puresky', name: 'Dusk' },
  { id: 'syferfontein_1d_clear_puresky', name: 'Low polar sun' },
];

const km = 1000;

export const SCENARIOS = [
  {
    id: 'trinity',
    numeral: 'I',
    name: 'TRINITY',
    device: '“The Gadget”',
    date: '16 July 1945',
    time: '05:29:45 Mountain War Time',
    place: 'Jornada del Muerto desert, New Mexico, USA',
    coords: '33.6773° N, 106.4754° W',
    yieldKt: 24.8,
    yieldNote: '24.8 ± 2 kt (2021 re-analysis; originally 21 kt)',
    hob: 30.5,
    medium: 'air',
    burstLabel: 'Tower shot: 100 ft (30.5 m) steel tower',
    env: 'desert',
    crater: { radius: 40, depth: 1.4, glass: true, glassRadius: 330 },
    props: ['trinityTower', 'bunkers', 'shrubs'],
    classification: 'TOP SECRET // RESTRICTED DATA — DECLASSIFIED',
    tagline: 'The first. The one that proved it could be done.',
    briefing: [
      'Thunderstorms swept the Jornada del Muerto all night. The shot was slipped from 04:00 to 05:30 while the meteorologists argued and the physicists paced.',
      'Atop a 100-foot steel tower hangs “the Gadget”. Around it, in every direction, the desert is dark. Ten thousand yards south, in the S-10000 control bunker, Sam Allison begins the count. On the same radio frequency a distant station bleeds through: Tchaikovsky’s Serenade for Strings.',
      'At Base Camp, ten miles out, Enrico Fermi tears a sheet of paper into strips. He intends to drop them when the blast wave arrives and measure how far it pushes them.',
    ],
    aftermath: [
      'The flash lit the mountains “brighter than a dozen suns”. It was seen 250 miles away. The Army’s cover story: an ammunition magazine had exploded.',
      'Fermi’s paper strips drifted about 2.5 metres. His on-the-spot estimate: ~10 kilotons.',
      'Test director Kenneth Bainbridge turned to Oppenheimer: “Now we are all sons of bitches.”',
      'The tower was vaporised. The desert floor fused into a pale green glass, later named trinitite.',
    ],
    observers: [
      { id: 's10000', name: 'S-10000 control bunker', note: '9.1 km S · Oppenheimer, Bainbridge', pos: [0, 9144], eye: 1.7 },
      { id: 'basecamp', name: 'Base Camp', note: '16 km SW · Fermi’s paper strips', pos: [-11300, 11300], eye: 1.7 },
      { id: 'compania', name: 'Compañia Hill', note: '32 km NW · Teller, Feynman, the press', pos: [-22600, -22600], eye: 1.7 },
      { id: 'w10000', name: 'W-10000 shelter', note: '9.1 km W · instrumentation', pos: [-9144, 0], eye: 1.7 },
      { id: 'near', name: 'Tower close-up', note: '1.2 km SE · instrumentation bunker range', pos: [800, 900], eye: 3 },
      { id: 'aerial', name: 'B-29 observation aircraft', note: '8.5 km altitude, 20 km S', pos: [0, 20000], eye: 8500, air: true },
    ],
    defaultObserver: 's10000',
    photo: { t: 0.016, note: 'Julian Mack’s high-speed camera caught the fireball at 16 ms: ~200 m across.' },
    sources: ['Rhodes, The Making of the Atomic Bomb (1986)', 'Selby et al., Nuclear Technology 207 (2021)', 'LANL Trinity archives'],
  },
  {
    id: 'baker',
    numeral: 'II',
    name: 'CROSSROADS BAKER',
    device: '“Helen of Bikini”',
    date: '25 July 1946',
    time: '08:35 local',
    place: 'Bikini Lagoon, Marshall Islands',
    coords: '11.5886° N, 165.5098° E',
    yieldKt: 23,
    yieldNote: '23 kt',
    hob: -27,
    medium: 'underwater',
    burstLabel: 'Underwater: 90 ft (27 m) below LSM-60, lagoon depth 180 ft',
    env: 'lagoon',
    crater: null,
    props: ['fleet'],
    classification: 'JOINT TASK FORCE ONE — DECLASSIFIED',
    tagline: 'The first underwater nuclear explosion and, some said, the first nuclear disaster.',
    briefing: [
      'Ninety-five ships are anchored in Bikini Lagoon: battleships, carriers, submarines, and the captured Japanese battleship Nagato. Goats and pigs stand on their decks.',
      'The device hangs in a caisson 90 feet beneath landing ship LSM-60 in the middle of the fleet.',
      'Twenty-three days earlier, Shot Able airburst over the same fleet and disappointed the press. Baker will not.',
    ],
    aftermath: [
      'A hemisphere of condensation (the Wilson cloud) flashed over the lagoon and hid the column rising beneath it.',
      'A hollow water column 2,000 ft wide and over a mile high lifted two million tons of water and sand. The 27,000-ton USS Arkansas was lifted up with it and sank.',
      'A radioactive “base surge” of mist rolled across the fleet. USS Saratoga sank seven and a half hours later. Most surviving ships were too contaminated to save.',
      'Glenn Seaborg called it “the world’s first nuclear disaster”.',
    ],
    observers: [
      { id: 'mckinley', name: 'USS Mount McKinley', note: '18 km · task force flagship', pos: [-13000, 12500], eye: 20 },
      { id: 'bikini', name: 'Bikini Island camera towers', note: '6 km · high-speed cameras', pos: [5000, -3300], eye: 25 },
      { id: 'arkansas', name: 'USS Arkansas deck', note: '0.2 km · target battleship', pos: [-150, 80], eye: 18 },
      { id: 'lagoon2', name: 'Lagoon, 2 km', note: 'Target array edge', pos: [1400, 1400], eye: 6 },
      { id: 'aerial', name: 'Camera aircraft', note: '3 km altitude, 9 km out', pos: [-6500, 6500], eye: 3000, air: true },
    ],
    defaultObserver: 'bikini',
    photo: { t: 0.5, note: 'The Wilson cloud forms as the shock’s rarefaction cools the humid lagoon air.' },
    sources: ['Weisgall, Operation Crossroads (1994)', 'Glasstone & Dolan §2.50–2.66'],
  },
  {
    id: 'bravo',
    numeral: 'III',
    name: 'CASTLE BRAVO',
    device: '“Shrimp”',
    date: '1 March 1954',
    time: '06:45 local',
    place: 'Namu Island reef, Bikini Atoll',
    coords: '11.6975° N, 165.2711° E',
    yieldKt: 15000,
    yieldNote: '15 Mt (forecast: 6 Mt)',
    hob: 2,
    medium: 'surface',
    burstLabel: 'Surface: on a reef-side platform',
    env: 'atoll',
    crater: { radius: 1000, depth: 76, glass: false },
    props: ['palms', 'bunkers'],
    classification: 'JOINT TASK FORCE SEVEN — DECLASSIFIED',
    tagline: 'The largest American test. Two and a half times bigger than anyone predicted.',
    briefing: [
      'The engineers expected six megatons. An unforeseen reaction in the device’s fuel is about to more than double that.',
      'At the Station 70 firing bunker on Enyu island, twenty miles away, the firing party trusts the concrete walls. Upper-level winds have been shifting east toward inhabited atolls all night. The shot goes ahead.',
      'Eighty-five miles east, beyond the danger zone, the tuna trawler Daigo Fukuryū Maru (the Lucky Dragon No. 5) is hauling its long-lines.',
    ],
    aftermath: [
      'The fireball was nearly 7 km wide within a second. The cloud reached 14 km in a minute and 40 km within ten, then spread 100 km wide.',
      'The crater it left in the reef is 2 km across and 76 m deep. You can still see it from orbit.',
      'Hours later a white powder (pulverised, radioactive coral) fell like snow on Rongelap and on the Lucky Dragon’s deck. Radio operator Aikichi Kuboyama died that September.',
      'The world learned the word “fallout”.',
    ],
    observers: [
      { id: 'enyu', name: 'Station 70, Enyu island', note: '32 km SE · firing bunker', pos: [22600, 22600], eye: 3 },
      { id: 'estes', name: 'USS Estes', note: '55 km E · command ship', pos: [55000, 0], eye: 20 },
      { id: 'lucky', name: 'Daigo Fukuryū Maru', note: '145 km E · the Lucky Dragon', pos: [140000, 30000], eye: 5 },
      { id: 'reef', name: 'Reef edge, 20 km', note: 'Atoll islet, SW', pos: [-14000, 14000], eye: 2 },
      { id: 'aerial', name: 'Sampling aircraft', note: '12 km altitude, 60 km out', pos: [-42000, 42000], eye: 12000, air: true },
    ],
    defaultObserver: 'enyu',
    photo: { t: 1.0, note: 'At one second the fireball of Bravo was already ~7 km across.' },
    sources: ['DOE/NV-209 United States Nuclear Tests', 'Glasstone & Dolan', 'Hacker, Elements of Controversy (1994)'],
  },
  {
    id: 'tsar',
    numeral: 'IV',
    name: 'TSAR BOMBA',
    device: 'AN602 “Ivan”',
    date: '30 October 1961',
    time: '11:32 Moscow Time',
    place: 'Sukhoy Nos, Novaya Zemlya, USSR',
    coords: '73.8076° N, 54.5808° E',
    yieldKt: 50000,
    yieldNote: '≈50 Mt (design capacity 100 Mt, deliberately halved)',
    hob: 4000,
    medium: 'air',
    burstLabel: 'Airburst: 4,000 m, parachute-retarded free-fall',
    env: 'arctic',
    crater: null,
    props: ['tu95'],
    classification: 'СОВЕРШЕННО СЕКРЕТНО — РАССЕКРЕЧЕНО',
    tagline: 'The largest explosion humanity has ever made.',
    briefing: [
      'A Tu-95V bomber, painted anti-flash white, climbs to 10.5 km over the Arctic archipelago. Its bomb bay doors could not close around the 27-tonne weapon.',
      'Major Andrei Durnovtsev and his crew were told they had a fifty-percent chance of surviving. An 800-kg parachute will slow the bomb’s fall for 188 seconds so the aircraft can run.',
      'A Tu-16 laboratory aircraft flies alongside to film the event.',
    ],
    aftermath: [
      'The fireball was 8 km across. Its own reflected shock kept it from touching the ground.',
      'The flash was seen 1,000 km away. The cloud climbed to ~64–67 km, seven times the height of Everest, and spread 95 km wide.',
      'The shock wave knocked the Tu-95V down 1 km before the crew regained control. The pressure wave circled the Earth three times.',
      'Wooden houses were destroyed hundreds of kilometres away; windows broke in Norway and Finland.',
    ],
    observers: [
      { id: 'tu95', name: 'Tu-95V cockpit', note: '45 km slant · Durnovtsev’s crew', pos: [-44000, 0], eye: 10500, air: true },
      { id: 'tu16', name: 'Tu-16 laboratory aircraft', note: '55 km · filming', pos: [-40000, 38000], eye: 10000, air: true },
      { id: 'post', name: 'Ground film post', note: '100 km S', pos: [0, 100000], eye: 60 },
      { id: 'severny', name: 'Severny settlement', note: '55 km', pos: [30000, 46000], eye: 2 },
      { id: 'near', name: 'Snowfield, 20 km', note: 'Inside the 5 psi zone', pos: [14000, 14000], eye: 2 },
    ],
    defaultObserver: 'tu16',
    photo: { t: 0.08, note: 'Even the early fireball of Tsar Bomba was kilometres wide.' },
    sources: ['Adamsky & Smirnov, CWIHP Bulletin 4 (1994)', 'Rosatom archive film (2020)'],
  },
];

export const CUSTOM = {
  id: 'custom',
  numeral: 'V',
  name: 'CUSTOM DETONATION',
  device: 'Hypothetical',
  date: 'Any date',
  time: '',
  place: 'Choose an environment',
  coords: '',
  yieldKt: 100,
  yieldNote: 'Any yield from 10 tonnes to 100 megatons',
  hob: 0,
  medium: 'surface',
  burstLabel: 'Adjustable',
  env: 'desert',
  crater: null,
  props: ['testArray', 'shrubs'],
  classification: 'SANDBOX',
  tagline: 'What if? Set the yield, altitude and place, and see the physics.',
  briefing: [
      'The historical tests are fixed points. Here, everything moves.',
      'A test array of frame houses, trees, utility poles and vehicles runs east from ground zero, with a structure every few hundred metres. Each one responds to its own peak overpressure, wind and thermal fluence.',
    'Set the yield, raise or lower the burst, change the sky, then watch the rings grow.',
  ],
  aftermath: [],
  observers: [
    { id: 'array', name: 'Test array, 3 km E', note: 'Looking back at zero', pos: [3000, 400], eye: 1.7 },
    { id: 'far', name: 'Observation post, 15 km', note: 'Safe distance?', pos: [-9000, 12000], eye: 1.7 },
    { id: 'near', name: 'Close, 1 km', note: 'Brave', pos: [700, 700], eye: 1.7 },
    { id: 'aerial', name: 'Aircraft, 10 km altitude', note: '30 km out', pos: [-21000, 21000], eye: 10000, air: true },
  ],
  defaultObserver: 'array',
  photo: { t: 0.001, note: 'Rapatronic cameras used magneto-optic shutters with ~10 ns exposures.' },
  sources: ['Glasstone & Dolan, The Effects of Nuclear Weapons (1977)'],
};

export function getScenario(id) {
  return SCENARIOS.find((s) => s.id === id) || (id === 'custom' ? CUSTOM : SCENARIOS[0]);
}
